import Link from "next/link";

export default function LegalPage() {
  return (
    <div className="min-h-screen bg-[#050505] text-slate-300 font-sans selection:bg-[#00e5b5] selection:text-black">
      
      <nav className="flex items-center justify-between px-6 py-4 border-b border-[#1a1a1a] bg-[#050505] sticky top-0 z-50">
        <div className="flex items-center gap-3">
          <Link href="/" className="w-8 h-8 rounded-lg bg-gradient-to-br from-[#00e5b5] to-[#008f71] flex items-center justify-center cursor-pointer">
            <span className="text-black font-bold text-lg">T</span>
          </Link>
          <span className="text-xl font-bold text-white border-l border-[#333] pl-3 ml-1">Legal & Policies</span>
        </div>
        <Link href="/" className="text-sm font-medium text-slate-400 hover:text-white transition-colors">
           ← Back to Home
        </Link>
      </nav>

      <div className="max-w-[800px] mx-auto py-12 px-6">
         <div className="space-y-16">
            
            <section id="license" className="scroll-mt-24">
               <h2 className="text-3xl font-bold text-white mb-6 pb-2 border-b border-[#1a1a1a]">Apache 2.0 License</h2>
               <p className="text-slate-400 leading-relaxed mb-4">
                 Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
               </p>
               <p className="text-slate-400 leading-relaxed">
                 Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND.
               </p>
            </section>

            <section id="privacy" className="scroll-mt-24">
               <h2 className="text-3xl font-bold text-white mb-6 pb-2 border-b border-[#1a1a1a]">Privacy Policy</h2>
               <p className="text-slate-400 leading-relaxed mb-4">
                 We do not store your OpenAI API keys on our servers. All API keys are passed directly to the LLM provider. 
               </p>
               <p className="text-slate-400 leading-relaxed">
                 We only cache the output generated by the LLM to save you tokens in future requests. You can clear your edge cache at any time via the developer dashboard.
               </p>
            </section>

            <section id="terms" className="scroll-mt-24">
               <h2 className="text-3xl font-bold text-white mb-6 pb-2 border-b border-[#1a1a1a]">Terms of Service</h2>
               <p className="text-slate-400 leading-relaxed mb-4">
                 By using TokenTrim, you agree to not abuse the free tier of the edge caching network. 
                 Accounts found to be spamming the edge network will be rate-limited or permanently suspended.
               </p>
            </section>

         </div>
      </div>
    </div>
  );
}
